version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf

  app:
    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
