openapi: 3.0.0
info:
  title: Social_Creators_teamG
  version: 0.0.0
servers:
- url: https://virtserver.swaggerhub.com/Khmer495/Social_Creators_teamG/0.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
